
-- Source: http://uhesse.com/2010/04/21/performance-impact-of-logical-standby-on-the-primary/
-- Create a table without Primary/Unique Columns and relatively many columns
-- That created a table with 200.000 rows and 176 MB in size. We will now record statistics under normal circumstances 
-- when no Logical Standby is present.


create table sales as select
rownum as id,
mod(rownum,5) as channel_id,
mod(rownum,1000) as cust_id,
5000 as amount_sold,
sysdate as time_id,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col1,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col2,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col3,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col4,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col5,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col6,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col7,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col8,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col9,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col10,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col11,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col12,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col13,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col14,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col15,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col16,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col17,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col18,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col19,
'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' as col20
from dual connect by level<=2e5;
