 DUPLICATE TARGET DATABASE
   FOR STANDBY
   FROM ACTIVE DATABASE
   DORECOVER
   SPFILE
     SET DB_UNIQUE_NAME='STBY_DB_UNIQUE_NAME'
     SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST  valid_for=(all_logfiles,all_roles) db_unique_name=STBY_DB_UNIQUE_NAME'
     SET LOG_ARCHIVE_DEST_2='SERVICE=PRIM_DB_UNIQUE_NAME lgwr async valid_for=(online_logfiles,primary_role) db_unique_name=PRIM_DB_UNIQUE_NAME'
     SET FAL_CLIENT='STBY_DB_UNIQUE_NAME'
     SET FAL_SERVER='PRIM_DB_UNIQUE_NAME'
     SET REMOTE_LISTENER='stby-scan:1522'
     SET AUDIT_FILE_DEST='ORACLE_BASE/admin/STBY_DB_UNIQUE_NAME/adump'
   NOFILENAMECHECK;
